### ISSUE TITLE
What is AzureEndpoint?

### ISSUE THREAD

**Issue by patgmac** [okieselbach/Munki-Middleware-Azure-Storage#1]
https://github.com/okieselbach/Munki-Middleware-Azure-Storage/blob/0eb5da968aa82e45439aa5d3bb701d953b4e9404/middleware_azure.py#L71

I'm curious what AzureEndpoint refers to in this line. Is that a pref you have set?

**Comment by okieselbach** [comment]
Yes, exactly this is a preference item I set via a .mobileconfig... but funny enough I missed to change it in the python script as I did a rework and renamed it to SotwareRepoURL see here: https://github.com/okieselbach/Intune/blob/master/macOS/munki-repo-and-sas.mobileconfig. I blogged about my complete approach here: https://oliverkieselbach.com/2021/07/14/comprehensive-guide-to-managing-macos-with-intune/
Luckly, I added the 'or' at the time of writing to prevent a failure in case of renaming... this is what happened. If you compare the .mobileConfig you will see the preference item now is named SoftwareRepoURL.
I'll fix this. 👍
